name: e_bandobas1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-222.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  get_cli: ^1.8.1
  get: ^4.6.5
  responsive_grid_list: ^1.3.0
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/